services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nakdong-network

  db:
    build: ./sql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: nakdong
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nakdong-network

networks:
  nakdong-network:
    driver: bridge

volumes:
  mysql-data:
